version: "3.9"

services:
  db:
    container_name: database-tg-bot
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=tiktoktelegramforever
      - POSTGRES_DB=tiktok_tg
      - DATABASE_HOST=db
    ports:
      - "6962:5432"
    networks:
      - tg_network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  tiktok-bot:
    container_name: "tiktok-tg-bot"
    build: .
    depends_on:
      - db
    networks:
      - tg_network
    restart: unless-stopped

networks:
  tg_network:
    driver: bridge


